services:
  # node:
  #   # image: node:16-bullseye-slim
  #   image: rkunihiro/nest9-node:latest
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest9-container-node
  #   networks:
  #     - default
  #   ports:
  #     - 4000:4000
  #   platform: linux/amd64

  # builder:
  #   # image: node:16-bullseye-slim
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-builder
  #   container_name: nest9-container-builder
  #   networks:
  #     - default
  #   platform: linux/amd64
  #   ports:
  #     - 4001:4000
  #   volumes:
  #     - .:/app:cached
  #   working_dir: /app
  #   tty: true

  # prod:
  #   image: gcr.io/distroless/nodejs-debian11:16
  #   container_name: nest9-container-prod
  #   environment:
  #     LANG: C.UTF-8
  #     NODE_ENV: production
  #     TZ: UTC
  #   networks:
  #     - default
  #   ports:
  #     - 3001:3000
  #   volumes:
  #     - ./dist:/app:ro
  #   working_dir: /app
  #   command: ['main.js']

  redis:
    image: redis:6.2.7-bullseye
    container_name: nest9-container-redis
    networks:
      - default
    ports:
      - 6379:6379

networks:
  default:
    name: nest9-network-default
